version: '3.8'

services:
  # ────────────────────── Traefik ──────────────────────
  mspr-api-infra:
    image: traefik:v2.10
    platform: linux/amd64
    ports:
      - "80:80"
      - "8080:8080"
    labels:
    - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
    - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - mspr-api-clients
      - mspr-api-produits
      - mspr-api-commandes
    networks: [mspr-network]

  # ────────────────────── APIs FastAPI ──────────────────────
  mspr-api-clients:
    image: ghcr.io/mgaisnon/mspr-api-clients:latest
    platform: linux/amd64
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mspr-db-clients:3306/clients_db
    depends_on: [mspr-db-clients, mspr-rabbitmq]
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.clients.rule=PathPrefix(`/clients`)"
    - "traefik.http.routers.clients.middlewares=clients-strip"
    - "traefik.http.middlewares.clients-strip.stripprefix.prefixes=/clients"
    - "traefik.http.services.clients.loadbalancer.server.port=8000"
    networks: [mspr-network]

  mspr-api-produits:
    image: ghcr.io/mgaisnon/mspr-api-produits:latest
    platform: linux/amd64
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mspr-db-produits:3306/produits_db
    depends_on: [mspr-db-produits, mspr-rabbitmq]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.produits.rule=PathPrefix(`/produits`)"
      - "traefik.http.routers.produits.middlewares=produits-strip"
      - "traefik.http.middlewares.produits-strip.stripprefix.prefixes=/produits"
      - "traefik.http.services.produits.loadbalancer.server.port=8001"
    networks: [mspr-network]

  mspr-api-commandes:
    image: ghcr.io/mgaisnon/mspr-api-commandes:latest
    platform: linux/amd64
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mspr-db-commandes:3306/commandes_db
    depends_on: [mspr-db-commandes, mspr-rabbitmq]
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.commandes.rule=PathPrefix(`/commandes`)"
    - "traefik.http.routers.commandes.middlewares=commandes-strip"
    - "traefik.http.middlewares.commandes-strip.stripprefix.prefixes=/commandes"
    - "traefik.http.services.commandes.loadbalancer.server.port=8002"
    networks: [mspr-network]

  # ────────────────────── Bases MySQL ──────────────────────
  mspr-db-clients:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=clients_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - clients_data:/var/lib/mysql
    networks: [mspr-network]

  mspr-db-produits:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=produits_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - produits_data:/var/lib/mysql
    networks: [mspr-network]

  mspr-db-commandes:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=commandes_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - commandes_data:/var/lib/mysql
    networks: [mspr-network]

  # ────────────────────── RabbitMQ ──────────────────────
  mspr-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
    - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    networks: [mspr-network]

  # ────────────────────── Prometheus ──────────────────────
  mspr-prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
    - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: [mspr-network]

  # ────────────────────── Grafana ──────────────────────
  mspr-grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
    - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards.yml
      - ./monitoring/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources.yml
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    networks: [mspr-network]

# Réseau commun
networks:
  mspr-network:
    driver: bridge

# Volumes persistants
volumes:
  clients_data:
  produits_data:
  commandes_data:
  grafana_data:
