version: '3.8'
services:
  mspr-api-infra:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - mspr-api-clients
      - mspr-api-produits
      - mspr-api-commandes
    networks:
      - mspr-network

  mspr-api-clients:
    image: ghcr.io/mgaisnon/mspr-api-clients:latest
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mspr-db-clients:3306/clients_db
    depends_on:
      - mspr-db-clients
      - mspr-rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.clients.rule=PathPrefix(`/clients`)"
      - "traefik.http.services.clients.loadbalancer.server.port=8000"
    networks:
      - mspr-network

  mspr-db-clients:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=clients_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - clients_data:/var/lib/mysql
    networks:
      - mspr-network

  mspr-api-produits:
    image: ghcr.io/mgaisnon/mspr-api-produits:latest
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mspr-db-produits:3306/produits_db
    depends_on:
      - mspr-db-produits
      - mspr-rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.produits.rule=PathPrefix(`/produits`)"
      - "traefik.http.services.produits.loadbalancer.server.port=8000"
    networks:
      - mspr-network

  mspr-db-produits:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=produits_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - produits_data:/var/lib/mysql
    networks:
      - mspr-network

  mspr-api-commandes:
    image: ghcr.io/mgaisnon/mspr-api-commandes:latest
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mspr-db-commandes:3306/commandes_db
    depends_on:
      - mspr-db-commandes
      - mspr-rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.commandes.rule=PathPrefix(`/commandes`)"
      - "traefik.http.services.commandes.loadbalancer.server.port=8000"
    networks:
      - mspr-network

  mspr-db-commandes:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=commandes_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - commandes_data:/var/lib/mysql
    networks:
      - mspr-network

  mspr-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mspr-network

  mspr-prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mspr-network

  mspr-grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - mspr-network

networks:
  mspr-network:
    driver: bridge

volumes:
  clients_data:
  produits_data:
  commandes_data: