http:
  routers:
    clients:
      rule: "PathPrefix(`/clients`)"
      service: api-clients
      middlewares:
        - strip-clients

    produits:
      rule: "PathPrefix(`/produits`)"
      service: api-produits

    commandes:
      rule: "PathPrefix(`/commandes`)"
      service: api-commandes

    grafana:
      rule: "PathPrefix(`/grafana`)"
      service: grafana

    rabbitmq:
      rule: "PathPrefix(`/rabbitmq`)"
      service: rabbitmq

  middlewares:
    strip-clients:
      stripPrefix:
        prefixes: ["/clients"]

  services:
    api-clients:
      loadBalancer:
        servers:
          - url: "https://mspr-api-clients.fly.dev"

    api-produits:
      loadBalancer:
        servers:
          - url: "https://mspr-api-produits.fly.dev"

    api-commandes:
      loadBalancer:
        servers:
          - url: "https://mspr-api-commandes.fly.dev"

    grafana:
      loadBalancer:
        servers:
          - url: "https://mspr-grafana.fly.dev"

    rabbitmq:
      loadBalancer:
        servers:
          - url: "https://mspr-rabbitmq.fly.dev"
