services:
  api-clients:
    image: ${IMG_API_CLIENTS:?set IMG_API_CLIENTS}
    build: null
    environment:
      DATABASE_URL: postgresql://clientuser:clientpass@db-clients:5432/clientsdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db-clients
      - rabbitmq

  api-produits:
    image: ${IMG_API_PRODUITS:?set IMG_API_PRODUITS}
    build: null
    environment:
      DATABASE_URL: postgresql://produituser:produitpass@db-produits:5432/produitsdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db-produits
      - rabbitmq

  api-commandes:
    image: ${IMG_API_COMMANDES:?set IMG_API_COMMANDES}
    build: null
    environment:
      DATABASE_URL: postgresql://commandeuser:commandepass@db-commandes:5432/commandesdb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db-commandes
      - rabbitmq
