# fly.toml app configuration file generated for mspr-prometheus on 2025-09-01T09:44:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mspr-prometheus'
primary_region = 'cdg'

[build]

[[mounts]]
  source = 'prometheus_data'
  destination = '/prometheus'

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
