app = "mspr-rabbitmq"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 15672
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
