app = "mspr-rabbitmq"
primary_region = "cdg"

[build]
  image = "rabbitmq:3.13-management"

[env]
  RABBITMQ_DEFAULT_USER = "guest"
  RABBITMQ_DEFAULT_PASS = "guest"

[mounts]
  source = "rabbitmq_data"
  destination = "/var/lib/rabbitmq"

[[services]]
  internal_port = 5672
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["tls"]
    port = 5672

[[services]]
  internal_port = 15672
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
